#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
#  JanMat — Developer Onboarding  (run this, NOT setup.sh)
#
#  What it does:
#    1. Authenticates your gcloud to the shared project
#    2. Sets ADC quota project (fixes the warning)
#    3. Pulls all secrets from Secret Manager → local .env files
#    4. Installs Python deps (backend)
#    5. Installs Node deps (dashboard)
#    6. Verifies your access is working
#
#  Prerequisites:
#    - gcloud CLI installed  → https://cloud.google.com/sdk/docs/install
#    - git clone of this repo
#    - Owner must have already run setup.sh AND granted you access
#      (or run:  ./infra/scripts/grant_dev_access.sh YOUR_EMAIL)
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

PROJECT_ID="project-f0fb8de7-7240-4128-965"
REGION="asia-south1"

BOLD='\033[1m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }
step() { echo -e "\n${BOLD}━━━ $1 ━━━${NC}"; }

# ── Prerequisites ────────────────────────────────────────────────────
step "Checking prerequisites"
command -v gcloud  >/dev/null || err "gcloud CLI not found → https://cloud.google.com/sdk/docs/install"
command -v python3 >/dev/null || err "python3 not found"
log "gcloud: $(gcloud version --format='value(Google Cloud SDK)' 2>/dev/null | head -1)"

# ── Auth ─────────────────────────────────────────────────────────────
step "Google account login"

# Interactive login (opens browser)
if ! gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | grep -q "@"; then
  warn "No active gcloud account — opening browser..."
  gcloud auth login --quiet
fi

ACTIVE_ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format='value(account)' | head -1)
log "Logged in as: $ACTIVE_ACCOUNT"

gcloud config set project "$PROJECT_ID" --quiet
log "Project set: $PROJECT_ID"

# ADC login (needed for SDK calls in Python/Node code)
warn "Setting up Application Default Credentials (ADC)..."
gcloud auth application-default login --quiet
gcloud auth application-default set-quota-project "$PROJECT_ID" --quiet
log "ADC configured — no more quota-project warning"

# ── Verify project access ────────────────────────────────────────────
step "Verifying GCP access"
if ! gcloud projects describe "$PROJECT_ID" --quiet &>/dev/null; then
  err "Cannot access project $PROJECT_ID. Ask the owner to run:
  ./infra/scripts/grant_dev_access.sh $ACTIVE_ACCOUNT"
fi
log "Project access confirmed"

# ── Pull secrets → .env files ────────────────────────────────────────
step "Pulling secrets from Secret Manager → .env files"

_secret() {
  gcloud secrets versions access latest \
    --secret="$1" --project="$PROJECT_ID" 2>/dev/null || echo ""
}

BACKEND_URL=$(gcloud run services describe janmat-backend \
  --region="$REGION" --project="$PROJECT_ID" \
  --format='value(status.url)' 2>/dev/null || echo "http://localhost:8080")

JWT_SECRET=$(_secret "janmat-jwt-secret")
MAPS_KEY=$(_secret "janmat-maps-api-key")
GOOGLE_CLIENT_ID=$(_secret "janmat-google-client-id")
GOOGLE_CLIENT_SECRET=$(_secret "janmat-google-client-secret")

DB_CONNECTION=$(gcloud sql instances describe janmat-db-poc \
  --project="$PROJECT_ID" \
  --format='value(connectionName)' 2>/dev/null || echo "")

# backend/.env
cat > backend/.env <<EOF
# Auto-generated by dev-setup.sh — do NOT commit
GCP_PROJECT_ID=${PROJECT_ID}
GCP_REGION=${REGION}
GEMINI_MODEL=gemini-3.1-flash-lite
GCS_MEDIA_BUCKET=janmat-media-${PROJECT_ID}
PUBSUB_TOPIC_GRIEVANCE_SUBMITTED=grievance-submitted
PUBSUB_TOPIC_PROCESSING_COMPLETE=processing-complete
PUBSUB_TOPIC_PRIORITY_UPDATED=priority-updated
BQ_ANALYTICS_DATASET=janmat_analytics
BQ_INFRASTRUCTURE_DATASET=janmat_infrastructure
CONSTITUENCY_ID=KA-BLR-NORTH-01
JWT_SECRET=${JWT_SECRET}
# DATABASE_URL is injected at runtime via Cloud SQL connector in Cloud Run
# For local dev with cloud-sql-proxy:
# DATABASE_URL=postgresql+asyncpg://janmat_user:PASSWORD@localhost:5432/janmat
EOF
log "backend/.env written"

# dashboard/.env
cat > dashboard/.env <<EOF
# Auto-generated by dev-setup.sh — do NOT commit
JANMAT_API_URL=${BACKEND_URL}
SESSION_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_CALLBACK_URL=http://localhost:3000/auth/google/callback
ALLOWED_MP_EMAILS=quantumduobuilder@gmail.com,${ACTIVE_ACCOUNT}
DEMO_MODE=true
DEMO_USER=mp@janmat.demo
DEMO_PASS=JanMat@2025!
MAPS_API_KEY=${MAPS_KEY}
EOF
log "dashboard/.env written"

[[ -z "$MAPS_KEY"   ]] && warn "Maps API key not in Secret Manager — dashboard heatmap will be blank"
[[ -z "$JWT_SECRET" ]] && warn "JWT secret missing — backend auth won't work"

# ── Python deps ──────────────────────────────────────────────────────
step "Installing Python dependencies (backend)"
cd backend
pip3 install -r requirements.txt --quiet --break-system-packages 2>/dev/null || \
  pip3 install -r requirements.txt --quiet
cd ..
log "Python deps installed"

# ── Node deps ────────────────────────────────────────────────────────
step "Installing Node.js dependencies (dashboard)"
if command -v node >/dev/null; then
  cd dashboard
  npm install --silent
  cd ..
  log "Node deps installed"
else
  warn "Node.js not found — install from https://nodejs.org (v18+)"
  warn "Then run:  cd dashboard && npm install"
fi

# ── Flutter deps ─────────────────────────────────────────────────────
step "Flutter citizen app"
if command -v flutter >/dev/null; then
  cd citizen-app
  flutter pub get --quiet
  cd ..
  log "Flutter deps resolved"
else
  warn "Flutter not found — install from https://flutter.dev/docs/get-started/install"
  warn "Then run:  cd citizen-app && flutter pub get"
fi

# ── Done ─────────────────────────────────────────────────────────────
step "✅  Dev setup complete"
echo ""
echo -e "${GREEN}${BOLD}You're ready to develop!${NC}"
echo ""
echo "  Start backend (local):   cd backend && uvicorn app.main:app --reload --port 8080"
echo "  Start dashboard (local): cd dashboard && npm start"
echo "  Run Flutter app:         cd citizen-app && flutter run"
echo "  API docs:                http://localhost:8080/docs"
echo "  Live backend:            $BACKEND_URL"
echo ""
echo -e "${YELLOW}DB access (Cloud SQL):${NC}"
if [[ -n "$DB_CONNECTION" ]]; then
  echo "  cloud-sql-proxy $DB_CONNECTION &"
  echo "  psql postgresql://janmat_user:PASSWORD@localhost:5432/janmat"
else
  echo "  gcloud sql connect janmat-db-poc --user=janmat_user --project=$PROJECT_ID"
fi
echo ""
echo -e "${RED}⚠  Never commit .env files or .db_password${NC}"
