"""
seed_bigquery.py — Load mock public infrastructure data into BigQuery

Usage:
    python infra/scripts/seed_bigquery.py --project YOUR_PROJECT_ID [--constituency all|KA-BLR-NORTH-01|MH-PUN-WEST-01]

This seeds janmat_infrastructure.public_infrastructure with mock
Census 2011 + NFHS-5 style data.

Constituencies:
  KA-BLR-NORTH-01 — Bangalore North, Karnataka
  MH-PUN-WEST-01  — Pune West, Maharashtra  (added to demo multi-MP onboarding)
"""

import argparse
from google.cloud import bigquery

PROJECT_ID = None  # Set via --project arg
DATASET_ID = "janmat_infrastructure"
TABLE_ID = "public_infrastructure"

_NONE_FIELDS = {
    "primary_schools": None,
    "secondary_schools": None,
    "school_enrollment_rate": None,
    "nearest_secondary_school_km": None,
    "teen_travel_distance_km": None,
    "health_centers": None,
    "hospital_beds_per_1000": None,
    "nearest_hospital_km": None,
    "road_quality_score": None,
    "paved_road_coverage_pct": None,
    "piped_water_access_pct": None,
    "sanitation_coverage_pct": None,
    "open_defecation_free": None,
}

# ─────────────────────────────────────────
# Mock data: Bangalore North constituency
# Source: Census 2011 + NFHS-5 approximations
# ─────────────────────────────────────────
MOCK_ROWS = [
    # ── Education ───────────────────────────────────────────────────────────
    {
        "village_id": "VIL-001",
        "village_name": "Yelahanka Village",
        "latitude": 13.1007,
        "longitude": 77.5963,
        "constituency_id": "KA-BLR-NORTH-01",
        "ward_id": "WARD-04",
        "population": 12400,
        "category": "Education",
        "primary_schools": 2,
        "secondary_schools": 0,
        "school_enrollment_rate": 0.61,
        "nearest_secondary_school_km": 8.2,
        "teen_travel_distance_km": 10.1,
        "health_centers": None,
        "hospital_beds_per_1000": None,
        "nearest_hospital_km": None,
        "road_quality_score": None,
        "paved_road_coverage_pct": None,
        "piped_water_access_pct": None,
        "sanitation_coverage_pct": None,
        "open_defecation_free": None,
        "data_source": "NFHS5",
        "reference_year": 2021,
        "last_updated": "2024-01-01",
    },
    {
        "village_id": "VIL-002",
        "village_name": "Kogilu Cross",
        "latitude": 13.0912,
        "longitude": 77.6034,
        "constituency_id": "KA-BLR-NORTH-01",
        "ward_id": "WARD-05",
        "population": 8700,
        "category": "Education",
        "primary_schools": 1,
        "secondary_schools": 0,
        "school_enrollment_rate": 0.54,
        "nearest_secondary_school_km": 6.5,
        "teen_travel_distance_km": 8.4,
        "health_centers": None,
        "hospital_beds_per_1000": None,
        "nearest_hospital_km": None,
        "road_quality_score": None,
        "paved_road_coverage_pct": None,
        "piped_water_access_pct": None,
        "sanitation_coverage_pct": None,
        "open_defecation_free": None,
        "data_source": "NFHS5",
        "reference_year": 2021,
        "last_updated": "2024-01-01",
    },
    {
        "village_id": "VIL-003",
        "village_name": "Jakkur Layout",
        "latitude": 13.0750,
        "longitude": 77.6100,
        "constituency_id": "KA-BLR-NORTH-01",
        "ward_id": "WARD-06",
        "population": 15200,
        "category": "Education",
        "primary_schools": 3,
        "secondary_schools": 1,
        "school_enrollment_rate": 0.72,
        "nearest_secondary_school_km": 3.1,
        "teen_travel_distance_km": 4.2,
        "health_centers": None,
        "hospital_beds_per_1000": None,
        "nearest_hospital_km": None,
        "road_quality_score": None,
        "paved_road_coverage_pct": None,
        "piped_water_access_pct": None,
        "sanitation_coverage_pct": None,
        "open_defecation_free": None,
        "data_source": "Census2011",
        "reference_year": 2011,
        "last_updated": "2024-01-01",
    },
    {
        "village_id": "VIL-004",
        "village_name": "Bagalur Village",
        "latitude": 13.1450,
        "longitude": 77.6280,
        "constituency_id": "KA-BLR-NORTH-01",
        "ward_id": "WARD-07",
        "population": 6200,
        "category": "Education",
        "primary_schools": 1,
        "secondary_schools": 0,
        "school_enrollment_rate": 0.48,
        "nearest_secondary_school_km": 12.3,
        "teen_travel_distance_km": 14.5,
        "health_centers": None,
        "hospital_beds_per_1000": None,
        "nearest_hospital_km": None,
        "road_quality_score": None,
        "paved_road_coverage_pct": None,
        "piped_water_access_pct": None,
        "sanitation_coverage_pct": None,
        "open_defecation_free": None,
        "data_source": "NFHS5",
        "reference_year": 2021,
        "last_updated": "2024-01-01",
    },
    # ── Health ──────────────────────────────────────────────────────────────
    {
        "village_id": "VIL-001",
        "village_name": "Yelahanka Village",
        "latitude": 13.1007,
        "longitude": 77.5963,
        "constituency_id": "KA-BLR-NORTH-01",
        "ward_id": "WARD-04",
        "population": 12400,
        "category": "Health",
        "primary_schools": None,
        "secondary_schools": None,
        "school_enrollment_rate": None,
        "nearest_secondary_school_km": None,
        "teen_travel_distance_km": None,
        "health_centers": 0,
        "hospital_beds_per_1000": 0.4,
        "nearest_hospital_km": 7.8,
        "road_quality_score": None,
        "paved_road_coverage_pct": None,
        "piped_water_access_pct": None,
        "sanitation_coverage_pct": None,
        "open_defecation_free": None,
        "data_source": "NFHS5",
        "reference_year": 2021,
        "last_updated": "2024-01-01",
    },
    {
        "village_id": "VIL-004",
        "village_name": "Bagalur Village",
        "latitude": 13.1450,
        "longitude": 77.6280,
        "constituency_id": "KA-BLR-NORTH-01",
        "ward_id": "WARD-07",
        "population": 6200,
        "category": "Health",
        "primary_schools": None,
        "secondary_schools": None,
        "school_enrollment_rate": None,
        "nearest_secondary_school_km": None,
        "teen_travel_distance_km": None,
        "health_centers": 0,
        "hospital_beds_per_1000": 0.2,
        "nearest_hospital_km": 15.4,
        "road_quality_score": None,
        "paved_road_coverage_pct": None,
        "piped_water_access_pct": None,
        "sanitation_coverage_pct": None,
        "open_defecation_free": None,
        "data_source": "NFHS5",
        "reference_year": 2021,
        "last_updated": "2024-01-01",
    },
    # ── Roads ───────────────────────────────────────────────────────────────
    {
        "village_id": "VIL-001",
        "village_name": "Yelahanka Village",
        "latitude": 13.1007,
        "longitude": 77.5963,
        "constituency_id": "KA-BLR-NORTH-01",
        "ward_id": "WARD-04",
        "population": 12400,
        "category": "Roads",
        "primary_schools": None,
        "secondary_schools": None,
        "school_enrollment_rate": None,
        "nearest_secondary_school_km": None,
        "teen_travel_distance_km": None,
        "health_centers": None,
        "hospital_beds_per_1000": None,
        "nearest_hospital_km": None,
        "road_quality_score": 3.2,
        "paved_road_coverage_pct": 0.38,
        "piped_water_access_pct": None,
        "sanitation_coverage_pct": None,
        "open_defecation_free": None,
        "data_source": "OpenStreetMap",
        "reference_year": 2023,
        "last_updated": "2024-01-01",
    },
    {
        "village_id": "VIL-004",
        "village_name": "Bagalur Village",
        "latitude": 13.1450,
        "longitude": 77.6280,
        "constituency_id": "KA-BLR-NORTH-01",
        "ward_id": "WARD-07",
        "population": 6200,
        "category": "Roads",
        "primary_schools": None,
        "secondary_schools": None,
        "school_enrollment_rate": None,
        "nearest_secondary_school_km": None,
        "teen_travel_distance_km": None,
        "health_centers": None,
        "hospital_beds_per_1000": None,
        "nearest_hospital_km": None,
        "road_quality_score": 1.8,
        "paved_road_coverage_pct": 0.15,
        "piped_water_access_pct": None,
        "sanitation_coverage_pct": None,
        "open_defecation_free": None,
        "data_source": "OpenStreetMap",
        "reference_year": 2023,
        "last_updated": "2024-01-01",
    },
    # ── Water ───────────────────────────────────────────────────────────────
    {
        "village_id": "VIL-001",
        "village_name": "Yelahanka Village",
        "latitude": 13.1007,
        "longitude": 77.5963,
        "constituency_id": "KA-BLR-NORTH-01",
        "ward_id": "WARD-04",
        "population": 12400,
        "category": "Water",
        "primary_schools": None,
        "secondary_schools": None,
        "school_enrollment_rate": None,
        "nearest_secondary_school_km": None,
        "teen_travel_distance_km": None,
        "health_centers": None,
        "hospital_beds_per_1000": None,
        "nearest_hospital_km": None,
        "road_quality_score": None,
        "paved_road_coverage_pct": None,
        "piped_water_access_pct": 0.42,
        "sanitation_coverage_pct": 0.55,
        "open_defecation_free": False,
        "data_source": "NFHS5",
        "reference_year": 2021,
        "last_updated": "2024-01-01",
    },
    {
        "village_id": "VIL-002",
        "village_name": "Kogilu Cross",
        "latitude": 13.0912,
        "longitude": 77.6034,
        "constituency_id": "KA-BLR-NORTH-01",
        "ward_id": "WARD-05",
        "population": 8700,
        "category": "Water",
        "primary_schools": None,
        "secondary_schools": None,
        "school_enrollment_rate": None,
        "nearest_secondary_school_km": None,
        "teen_travel_distance_km": None,
        "health_centers": None,
        "hospital_beds_per_1000": None,
        "nearest_hospital_km": None,
        "road_quality_score": None,
        "paved_road_coverage_pct": None,
        "piped_water_access_pct": 0.31,
        "sanitation_coverage_pct": 0.47,
        "open_defecation_free": False,
        "data_source": "NFHS5",
        "reference_year": 2021,
        "last_updated": "2024-01-01",
    },
    # ── Sanitation ──────────────────────────────────────────────────────────
    {
        "village_id": "VIL-004",
        "village_name": "Bagalur Village",
        "latitude": 13.1450,
        "longitude": 77.6280,
        "constituency_id": "KA-BLR-NORTH-01",
        "ward_id": "WARD-07",
        "population": 6200,
        "category": "Sanitation",
        "primary_schools": None,
        "secondary_schools": None,
        "school_enrollment_rate": None,
        "nearest_secondary_school_km": None,
        "teen_travel_distance_km": None,
        "health_centers": None,
        "hospital_beds_per_1000": None,
        "nearest_hospital_km": None,
        "road_quality_score": None,
        "paved_road_coverage_pct": None,
        "piped_water_access_pct": None,
        "sanitation_coverage_pct": 0.22,
        "open_defecation_free": False,
        "data_source": "NFHS5",
        "reference_year": 2021,
        "last_updated": "2024-01-01",
    },
]


# ─────────────────────────────────────────
# Pune West constituency (MH-PUN-WEST-01)
# Synthetic data modelled on Census 2011 + NFHS-5 Maharashtra averages
# Demonstrates "new MP onboarded in minutes" multi-constituency capability
# ─────────────────────────────────────────
PUNE_WEST_ROWS = [
    # ── Education ───────────────────────────────────────────────────────────
    {**_NONE_FIELDS,
     "village_id": "VIL-P001", "village_name": "Warje Malwadi",
     "latitude": 18.4810, "longitude": 73.8098,
     "constituency_id": "MH-PUN-WEST-01", "ward_id": "PWARD-01",
     "population": 18600, "category": "Education",
     "primary_schools": 3, "secondary_schools": 1,
     "school_enrollment_rate": 0.67, "nearest_secondary_school_km": 4.8,
     "teen_travel_distance_km": 6.1,
     "data_source": "Census2011", "reference_year": 2011, "last_updated": "2024-01-01"},
    {**_NONE_FIELDS,
     "village_id": "VIL-P002", "village_name": "Bavdhan Khurd",
     "latitude": 18.5135, "longitude": 73.7705,
     "constituency_id": "MH-PUN-WEST-01", "ward_id": "PWARD-02",
     "population": 11200, "category": "Education",
     "primary_schools": 2, "secondary_schools": 0,
     "school_enrollment_rate": 0.59, "nearest_secondary_school_km": 7.3,
     "teen_travel_distance_km": 9.0,
     "data_source": "NFHS5", "reference_year": 2021, "last_updated": "2024-01-01"},
    {**_NONE_FIELDS,
     "village_id": "VIL-P003", "village_name": "Kothrud Extension",
     "latitude": 18.5065, "longitude": 73.8070,
     "constituency_id": "MH-PUN-WEST-01", "ward_id": "PWARD-03",
     "population": 24300, "category": "Education",
     "primary_schools": 5, "secondary_schools": 2,
     "school_enrollment_rate": 0.78, "nearest_secondary_school_km": 1.9,
     "teen_travel_distance_km": 2.4,
     "data_source": "Census2011", "reference_year": 2011, "last_updated": "2024-01-01"},
    {**_NONE_FIELDS,
     "village_id": "VIL-P004", "village_name": "Pirangut Village",
     "latitude": 18.5020, "longitude": 73.7240,
     "constituency_id": "MH-PUN-WEST-01", "ward_id": "PWARD-04",
     "population": 7400, "category": "Education",
     "primary_schools": 1, "secondary_schools": 0,
     "school_enrollment_rate": 0.45, "nearest_secondary_school_km": 11.6,
     "teen_travel_distance_km": 13.8,
     "data_source": "NFHS5", "reference_year": 2021, "last_updated": "2024-01-01"},
    # ── Health ──────────────────────────────────────────────────────────────
    {**_NONE_FIELDS,
     "village_id": "VIL-P001", "village_name": "Warje Malwadi",
     "latitude": 18.4810, "longitude": 73.8098,
     "constituency_id": "MH-PUN-WEST-01", "ward_id": "PWARD-01",
     "population": 18600, "category": "Health",
     "health_centers": 1, "hospital_beds_per_1000": 0.9, "nearest_hospital_km": 4.2,
     "data_source": "NFHS5", "reference_year": 2021, "last_updated": "2024-01-01"},
    {**_NONE_FIELDS,
     "village_id": "VIL-P004", "village_name": "Pirangut Village",
     "latitude": 18.5020, "longitude": 73.7240,
     "constituency_id": "MH-PUN-WEST-01", "ward_id": "PWARD-04",
     "population": 7400, "category": "Health",
     "health_centers": 0, "hospital_beds_per_1000": 0.3, "nearest_hospital_km": 14.7,
     "data_source": "NFHS5", "reference_year": 2021, "last_updated": "2024-01-01"},
    # ── Roads ───────────────────────────────────────────────────────────────
    {**_NONE_FIELDS,
     "village_id": "VIL-P002", "village_name": "Bavdhan Khurd",
     "latitude": 18.5135, "longitude": 73.7705,
     "constituency_id": "MH-PUN-WEST-01", "ward_id": "PWARD-02",
     "population": 11200, "category": "Roads",
     "road_quality_score": 2.4, "paved_road_coverage_pct": 0.28,
     "data_source": "OpenStreetMap", "reference_year": 2023, "last_updated": "2024-01-01"},
    {**_NONE_FIELDS,
     "village_id": "VIL-P004", "village_name": "Pirangut Village",
     "latitude": 18.5020, "longitude": 73.7240,
     "constituency_id": "MH-PUN-WEST-01", "ward_id": "PWARD-04",
     "population": 7400, "category": "Roads",
     "road_quality_score": 1.5, "paved_road_coverage_pct": 0.12,
     "data_source": "OpenStreetMap", "reference_year": 2023, "last_updated": "2024-01-01"},
    # ── Water ───────────────────────────────────────────────────────────────
    {**_NONE_FIELDS,
     "village_id": "VIL-P001", "village_name": "Warje Malwadi",
     "latitude": 18.4810, "longitude": 73.8098,
     "constituency_id": "MH-PUN-WEST-01", "ward_id": "PWARD-01",
     "population": 18600, "category": "Water",
     "piped_water_access_pct": 0.58, "sanitation_coverage_pct": 0.69, "open_defecation_free": False,
     "data_source": "NFHS5", "reference_year": 2021, "last_updated": "2024-01-01"},
    {**_NONE_FIELDS,
     "village_id": "VIL-P004", "village_name": "Pirangut Village",
     "latitude": 18.5020, "longitude": 73.7240,
     "constituency_id": "MH-PUN-WEST-01", "ward_id": "PWARD-04",
     "population": 7400, "category": "Water",
     "piped_water_access_pct": 0.24, "sanitation_coverage_pct": 0.35, "open_defecation_free": False,
     "data_source": "NFHS5", "reference_year": 2021, "last_updated": "2024-01-01"},
    # ── Sanitation ──────────────────────────────────────────────────────────
    {**_NONE_FIELDS,
     "village_id": "VIL-P002", "village_name": "Bavdhan Khurd",
     "latitude": 18.5135, "longitude": 73.7705,
     "constituency_id": "MH-PUN-WEST-01", "ward_id": "PWARD-02",
     "population": 11200, "category": "Sanitation",
     "sanitation_coverage_pct": 0.41, "open_defecation_free": False,
     "data_source": "NFHS5", "reference_year": 2021, "last_updated": "2024-01-01"},
]

ALL_ROWS = MOCK_ROWS + PUNE_WEST_ROWS


def seed(project_id: str, constituency: str = "all") -> None:
    client = bigquery.Client(project=project_id)
    table_ref = f"{project_id}.{DATASET_ID}.{TABLE_ID}"

    if constituency == "all":
        rows = ALL_ROWS
    elif constituency == "MH-PUN-WEST-01":
        rows = PUNE_WEST_ROWS
    elif constituency == "KA-BLR-NORTH-01":
        rows = MOCK_ROWS
    else:
        raise ValueError(f"Unknown constituency: {constituency}")

    errors = client.insert_rows_json(table_ref, rows)
    if errors:
        print(f"❌ BigQuery insert errors: {errors}")
        raise RuntimeError("Seed failed")

    print(f"✅ Seeded {len(rows)} rows into {table_ref} (constituency={constituency})")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", required=True, help="GCP Project ID")
    parser.add_argument(
        "--constituency", default="all",
        choices=["all", "KA-BLR-NORTH-01", "MH-PUN-WEST-01"],
        help="Which constituency to seed (default: all)",
    )
    args = parser.parse_args()
    seed(args.project, args.constituency)
